### ISSUE TITLE
Using the UI to update fcr:metadata does not show inserted properties 

### ISSUE THREAD

**Issue by christopher-johnson** [fcrepo4/fcrepo4#1034]
There are two distinct problems with fcr:metadata.

1)  using the UI to insert new properties does not show them in the UI, even though the update is successful.

However, if 
`curl -X PATCH -H "Content-Type: application/sparql-update" --data-binary "@body.rdf" "http://localhost:8080/rest/node/to/update/fcr:metadata"` is used, the new properties are shown in the UI and the update is successful.

2)  If properties are inserted in a fcr:metadata object with 
`curl -X PUT -H "Content-Type: text/turtle" --data-binary "@new-triples.rdf" "http://localhost:8080/rest/node/to/update/fcr:metadata"`, nothing happens and no data is saved.

**Comment by acoburn** [comment]
@christopher-johnson thanks for reporting this. This is actually a known issue, and it relates to how ETags are generated by Binary descriptions. This is already being tracked in https://jira.duraspace.org/browse/FCREPO-1983. I even have a fix for it, but that fix depends on a few other PRs currently in review. I will close this issue as it is already being tracked in JIRA.
