### ISSUE TITLE
Updating filename adds schema URI to Content-Disposition header

### ISSUE THREAD

**Issue by electrickite** [fcrepo4/fcrepo4#1145]
I am using Fedora 4.7.0 behind a Hydra application stack. I've run into an issue forcing me to update the "filename" (http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#filename) metadata attribute associated with each binary file in the repository. I tried unsuccessfully to do this via Hydra (same problem I'll describe below) so I went straight to the Fedora web UI to try a manual update.

I located one of the files, which had a file name defined like this:  ebucore:filename gh237hjdh

<img width="287" alt="screen shot 2016-11-22 at 2 47 50 pm" src="https://cloud.githubusercontent.com/assets/3449824/20539823/7c207734-b0c4-11e6-8594-3512570a819e.png">

I then issued the following update, from the "Update Properties" panel in the web UI:

    PREFIX premis: <http://www.loc.gov/premis/rdf/v1#>
    PREFIX nt: <http://www.jcp.org/jcr/nt/1.0>
    PREFIX ns022: <http://purl.org/vra/Material#>
    PREFIX ns021: <http://id.loc.gov/vocabulary/identifiers/>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    PREFIX ns020: <http://purl.org/vra/QuantitativeValue#>
    PREFIX ns004: <http://pcdm.org/models#>
    PREFIX ns003: <http://projecthydra.org/ns/auth/acl#>
    PREFIX ns002: <http://www.w3.org/ns/auth/acl#>
    PREFIX ns023: <http://www.w3.org/2011/content#>
    PREFIX ns001: <info:fedora/fedora-system:def/model#>
    PREFIX xsi: <http://www.w3.org/2001/XMLSchema-instance>
    PREFIX ns008: <https://library.osu.edu/ns#>
    PREFIX mode: <http://www.modeshape.org/1.0>
    PREFIX ns007: <http://projecthydra.org/works/models#>
    PREFIX xmlns: <http://www.w3.org/2000/xmlns/>
    PREFIX ns006: <http://projecthydra.org/ns/relations#>
    PREFIX ns005: <http://purl.org/dc/terms/>
    PREFIX audit: <http://fedora.info/definitions/v4/audit#>
    PREFIX xml: <http://www.w3.org/XML/1998/namespace>
    PREFIX ns009: <http://id.loc.gov/vocabulary/relators/>
    PREFIX jcr: <http://www.jcp.org/jcr/1.0>
    PREFIX fedoraconfig: <http://fedora.info/definitions/v4/config#>
    PREFIX mix: <http://www.jcp.org/jcr/mix/1.0>
    PREFIX prov: <http://www.w3.org/ns/prov#>
    PREFIX foaf: <http://xmlns.com/foaf/0.1/>
    PREFIX authz: <http://fedora.info/definitions/v4/authorization#>
    PREFIX image: <http://www.modeshape.org/images/1.0>
    PREFIX sv: <http://www.jcp.org/jcr/sv/1.0>
    PREFIX test: <info:fedora/test/>
    PREFIX ns011: <http://www.iana.org/assignments/relation/>
    PREFIX ns010: <http://www.openarchives.org/ore/terms/>
    PREFIX ns015: <http://projecthydra.org/ns/fits/>
    PREFIX ns014: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
    PREFIX ns013: <http://www.w3.org/2003/12/exif/ns#>
    PREFIX ns012: <http://pcdm.org/use#>
    PREFIX ns019: <info:fedora/fedora-system:def/relations-external#>
    PREFIX ns018: <http://purl.org/vra/>
    PREFIX ns017: <http://projecthydra.org/ns/mix/>
    PREFIX ns016: <http://sweet.jpl.nasa.gov/2.2/reprDataFormat.owl#>
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX fedora: <http://fedora.info/definitions/v4/repository#>
    PREFIX ebucore: <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#>
    PREFIX ldp: <http://www.w3.org/ns/ldp#>
    PREFIX xs: <http://www.w3.org/2001/XMLSchema>
    PREFIX dc: <http://purl.org/dc/elements/1.1/>    

    DELETE { <> ebucore:filename "gh237hjdh" }
    INSERT { <> ebucore:filename "newname.jpg" }
    WHERE { }

Which resulted in the expected change:  ebucore:filename newname.jpg

<img width="317" alt="screen shot 2016-11-22 at 2 48 33 pm" src="https://cloud.githubusercontent.com/assets/3449824/20539842/900107dc-b0c4-11e6-9bba-7586c0dc3d9d.png">

However, when I try to download the file, Fedora is sending a mangled file name in the content disposition header. It appends an XML schema URI to the file name: "newname.jpg ^^ http://www.w3.org/2001/XMLSchema#string"

<img width="440" alt="screen shot 2016-11-22 at 2 48 57 pm" src="https://cloud.githubusercontent.com/assets/3449824/20539854/9bd74922-b0c4-11e6-8175-c0c9bf9021d8.png">

A curl request confirmed the issue:

    $ curl -v http://localhost:8080/fcrepo/rest/prod/7w/62/f9/51/7w62f951h/files/40f22f18-afb5-4fed-84a1-b9906e7b0e98 -u USER
    Enter host password for user 'USER':
    *   Trying ::1...
    * Connected to localhost (::1) port 8080 (#0)
    * Server auth using Basic with user 'USER'
    > GET /fcrepo/rest/prod/7w/62/f9/51/7w62f951h/files/40f22f18-afb5-4fed-84a1-b9906e7b0e98 HTTP/1.1
    > Host: localhost:8080
    > Authorization: Basic XXXX
    > User-Agent: curl/7.49.1
    > Accept: */*
    >
    < HTTP/1.1 200 OK
    < Server: Apache-Coyote/1.1
    < Cache-Control: no-transform, must-revalidate, max-age=0
    < Expires: Wed, 31 Dec 1969 19:00:00 EST
    < ETag: "202c549347cd0700d731ec85dd97f39257777443"
    < Last-Modified: Sat, 19 Nov 2016 22:58:17 GMT
    < Accept-Ranges: bytes
    < Content-Disposition: attachment; filename="newname.jpg ^^ http://www.w3.org/2001/XMLSchema#string"; creation-date="Sat, 19 Nov 2016 22:58:17 GMT"; modification-date="Tue, 22 Nov 2016 19:24:48 GMT"; size=277448828
    < Link: <http://www.w3.org/ns/ldp#Resource>;rel="type"
    < Link: <http://www.w3.org/ns/ldp#NonRDFSource>;rel="type"
    < Link: <http://localhost:8080/fcrepo/rest/prod/32/8e/8e/dd/328e8edd-ab48-494b-bd05-ffafdc66f67a>; rel="acl"
    < Link: <http://localhost:8080/fcrepo/rest/prod/7w/62/f9/51/7w62f951h/files/40f22f18-afb5-4fed-84a1-b9906e7b0e98/fcr:metadata>; rel="describedby"
    < Allow: DELETE,HEAD,GET,PUT,OPTIONS
    < ETag: "202c549347cd0700d731ec85dd97f39257777443"
    < Last-Modified: Sat, 19 Nov 2016 22:58:17 GMT
    < Content-Type: image/tiff
    < Content-Length: 277448828
    < Date: Tue, 22 Nov 2016 19:27:18 GMT
    <

As I mentioned earlier, Ruby (via Hydra) exhibits the same symptoms, because it pulls the file name from Fedora's content disposition header.

I'm at a bit of a loss on how to proceed at this point. I'm hoping someone can either point me in the right direction if there's something else I need to do, or at least help confirm this is a bug in Fedora.

**Comment by escowles** [comment]
@electrickite Thanks for pointing this out — this is definitely a Fedora bug, and it should be sending the filename without the datatype URI.  I'm going to close this GitHub ticket and I've created a JIRA ticket to track this: https://jira.duraspace.org/browse/FCREPO-2317.
