### ISSUE TITLE
Response to range request returns full content-length if range size > 8192

### ISSUE THREAD

**Issue by ikreymer** [fcrepo4/fcrepo4#1211]
This issue repros with the Fedora 4.7, using the `cbeer/fcrepo4:4.7` docker image.

When requesting a range chunk with size >8192, the `Content-Length` appears to always be the full length, not the size of the returned chunk, although only the expected chunk is actual served. (This just causes curl to stall).

For exampe, a binary object with size of 689544:

If chunk size is <=8192
```
=> curl -v -r 0-8191 http://localhost:8080/fcrepo/rest/path/to/object
< Content-Range: bytes 0-8191/689544
< Content-Length: 8192
```

If chunk size is >8192
```
=> curl -v -r 0-8192 http://localhost:8080/fcrepo/rest/path/to/object
< Content-Range: bytes 0-8192/689544
< Content-Length: 689544
```

Appears to be dependent on the chunk size only, would see same behavior with `-r 100-8291` vs `-r 100-8292`

**Comment by escowles** [comment]
I've confirmed this issue and created a JIRA ticket to track it: https://jira.duraspace.org/browse/FCREPO-2536
