### ISSUE TITLE
fcrepo-http-api tests (and others?) use the slf4j no-op logger

### ISSUE THREAD

**Issue by cbeer** [fcrepo4/fcrepo4#507]
Probably for @ajs6f:

When running the fcrepo-http-api tests, we don't get any of the org.fcrepo module logging. The logs show slf4j can't find an implementation and defaults to a no-op logger. This used to work, so I assume we used to get logback through some transitive dependency (and no longer do). I assume we should provide a logger impl at least for `<scope>test</scope>`. What's the right way to do this? A hard dependency somewhere, a test-jar dependency in -kernel-impl, etc??

**Comment by awoods** [comment]
Resolved with: https://github.com/fcrepo4/fcrepo4/commit/58bdaa218af0d6a5501c7681d571047441a188ef#diff-b18f0fcac8119c409433b086dd91691d
