### ISSUE TITLE
When the tomcat user's home directory is unset, nonsensical directories are used

### ISSUE THREAD

**Issue by cbeer** [fcrepo4/fcrepo4#659]
When `fcrepo.home` isn't provided, we try to fallback on the home directory of the tomcat user. If the tomcat user is unset, though, we end up trying to create directories in `//fcrepo4-data`, which probably isn't what we intend to do.

https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/spring/DefaultPropertiesLoader.java#L89

**Comment by acoburn** [comment]
When `fcrepo.home` isn't provided, Fedora falls back to the JVM's current working directory (`user.dir`), not the user's home directory (`user.home`). Given that, it seems that the problematic directory `//fcrepo4-data` isn't something that would be created. @cbeer can you comment on whether you've seen these sorts of directories being created?
