### ISSUE TITLE
Web interface should sort children.

### ISSUE THREAD

**Issue by jcoyne** [fcrepo4/fcrepo4#676]
It's impossible to do anything useful with a giant unordered list.

![screen shot 2014-12-09 at 11 00 23 pm](https://cloud.githubusercontent.com/assets/92044/5371178/4bb8312c-7ff7-11e4-95b5-5710c89273eb.png)

**Comment by acoburn** [comment]
Closing this issue insofar as it is about the web interface sorting child resources.
