### ISSUE TITLE
fcrepo4-bom is including artifacts from the beta release

### ISSUE THREAD

**Issue by acoburn** [fcrepo4/fcrepo4#683]
See https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-boms/fcrepo4-bom/pom.xml#L25

(and line 30 below)

I assume this is not correct.

**Comment by awoods** [comment]
Yes, those version values should be: ${project.version}

**Comment by awoods** [comment]
Resolved with: https://github.com/fcrepo4/fcrepo4/commit/842e60c3584c61940116201363770dbc6e6c60d1
