### ISSUE TITLE
"java.text.ParseException: Next event is not a Separator" raised

### ISSUE THREAD

**Issue by jcoyne** [fcrepo4/fcrepo4#687]
when you pass a filename header with an unescaped quote in it.  It's fine for this to be an error, but is the java specific exception appropriate?

I set a header like this:
```
Content-Disposition: attachment; filename=" "Value Added" in Editorial Acquisitions.pdf"
```

**Comment by awoods** [comment]
Tracking with: https://jira.duraspace.org/browse/FCREPO-1295
