### ISSUE TITLE
409 when setting RDF.type to a string

### ISSUE THREAD

**Issue by jcoyne** [fcrepo4/fcrepo4#726]
```
D, [2015-02-17T18:32:34.590009 #34235] DEBUG -- :   HTTP HEAD (7.17ms)   http://localhost:8983/fedora/rest/test/cusbspcmss36_110108
D, [2015-02-17T18:32:34.590085 #34235] DEBUG -- :   Response status   Net::HTTPNotFound (404)
D, [2015-02-17T18:32:34.614986 #34235] DEBUG -- :   HTTP PUT (16.27ms)   http://localhost:8983/fedora/rest/test/cusbspcmss36_110108
D, [2015-02-17T18:32:34.615091 #34235] DEBUG -- :   Request body
<http://localhost:8983/fedora/rest/test/cusbspcmss36_110108> a "still image";
   <http://purl.org/dc/terms/title> "Arlington Hotel, Santa Barbara earthquake";
   <http://opaquenamespace.org/ns/vra/earliestDate> "";
   <http://opaquenamespace.org/ns/vra/latestDate> "";
   <http://purl.org/dc/terms/extent> "1 photograph ; 9 x 14 cm (postcard format)";
   <http://purl.org/dc/terms/issued> "1925";
   <http://purl.org/dc/terms/publisher> "[Cross & Dimmit Pictures]";
   <http://purl.org/dc/terms/spatial> <http://id.loc.gov/authorities/names/n79041717>;
   <http://purl.org/dc/terms/subject> <http://id.loc.gov/authorities/subjects/sh85062487>,
     <http://id.loc.gov/authorities/subjects/sh85040496>,
     <http://id.loc.gov/authorities/subjects/sh2014002461>;
   <http://www.rdaregistry.info/Elements/w/formOfWork.en> <http://vocab.getty.edu/aat/300192703>,
     <http://vocab.getty.edu/aat/300026816>,
     <http://vocab.getty.edu/aat/300046300>;
   <info:fedora/fedora-system:def/model#hasModel> "Image" .

D, [2015-02-17T18:32:34.616893 #34235] DEBUG -- :   Response status   Net::HTTPConflict (409)
D, [2015-02-17T18:32:34.616990 #34235] DEBUG -- :   Response body   org.modeshape.jcr.value.ValueFormatException: Error converting "still image" from String to a URI
```

**Comment by cbeer** [comment]
`409 Conflict` may not be the right response (`400 Bad Request`, perhaps?), but I don't think RDF lets you use a literal for `rdf:type`.

**Comment by acoburn** [comment]
@cbeer is correct -- the range for rdf:type is rdfs:Class, which means it can't be a literal.

**Comment by jcoyne** [comment]
Sounds good, but 409 is the wrong code and there shouldn't be showing a stack trace in the body. Something like "Invalid value for rdf:type" would be ideal

**Comment by ajs6f** [comment]
Whether the stack trace should be shown is not a sure "no". It should be adjustable, and I suspect that it is (it is for 500 errors).

**Comment by awoods** [comment]
It sounds like there are two issues at hand:
- 409 response code, or other
- Existing message (which appears to be a one line exception message, not a stacktrace), or other

This particular exception is translated into a "MalformedRdfException", which seems appropriate. We have MalformedRdfExceptions return a 409 status code (that can be changed if you feel like the more generic 400 is clearer). Also, in order to provide some hint to the client as to the source of the error, the exception message is included... which in this case seems very helpful. However, we could potentially filter out the `org.modeshape.jcr.value.ValueFormatException:` portion of that message, if that would be helpful.

Thoughts?

**Comment by jcoyne** [comment]
I don't think that Exceptions should be surfaced at the API (non-Java) level. It should be an error in a human readable terms. i.e. "Error parsing RDF. Couldn't convert 'still image' from String to a URI"

**Comment by awoods** [comment]
@jcoyne, that is reasonable regarding the message of the error. What would make sense to you regarding the status code?

**Comment by jcoyne** [comment]
I don't much care, but 409 is confusing -- 400 less so.

**Comment by escowles** [comment]
:+1: to using 400 for this -- I think 400 should be used for malformed/invalid RDF, and 409 for trying to create an existing node, referential integrity problems, etc.

**Comment by awoods** [comment]
Tracking issue in jira:
https://jira.duraspace.org/browse/FCREPO-1368
