### ISSUE TITLE
Receiving 409 PathNotFoundException?

### ISSUE THREAD

**Issue by jcoyne** [fcrepo4/fcrepo4#733]
Shouldn't this be a 404? get rid of the `javax.jcr.PathNotFoundException`

```
STATUS: 409 javax.jcr.PathNotFoundException: No node exists at path '/test/bf/74/27/75/bf742775-2a24-46dc-889e-cca03b27b5f3' in workspace "default"...
```

**Comment by ajs6f** [comment]
Depends on how the `PathNotFoundException` arose. Could be a 404, or a 409. Anyway, the message could be better.

**Comment by jcoyne** [comment]
I suspect this was caused by a PUT to a resource before it's parent was created.

**Comment by ajs6f** [comment]
Well, I'm no HTTP maven, so I welcome correction, but that does sound 409ish to me.

**Comment by jcoyne** [comment]
Okay, the problem I had was making a link to a resource that didn't exist yet (persisting a linked list). 409 seems appropriate. A more intelligible message might be: "You attempted to create a link to a repository resource that doesn't exist (URI: http://localhost:8080/foo/bar)"

**Comment by ajs6f** [comment]
That does sound like a much more useful message. Can you file a Jira ticket, or do you have access for that?

**Comment by awoods** [comment]
Tracking in JIRA: https://jira.duraspace.org/browse/FCREPO-1375
