### ISSUE TITLE
HTTP 500 null pointer exception with bad prefer header

### ISSUE THREAD

**Issue by hectorcorrea** [fcrepo4/fcrepo4#750]
The following commands result in an HTTP 500 and the return says "java.lang.NullPointerException..."

    curl -H "Prefer: return=minimal; " http://fedora4/SSqaFedora4/rest/prod/path/to/a/valid/resource

Notice the semicolon and space after minimal. The command works OK with the proper syntax ("return=minimal") but I was not expecting an HTTP 500 nor a NullPointerException in the message. I would suggest an HTTP 4xx return code instead and perhaps a better handling of the error on the server side.

**Comment by escowles** [comment]
Hector-

This is very easy to fix: I've created a JIRA ticket for this with PR coming shortly:

https://jira.duraspace.org/browse/FCREPO-1406
