### ISSUE TITLE
HTTP 500 after dodgy SPARQL Update is submitted via PATCH

### ISSUE THREAD

**Issue by adolski** [fcrepo4/fcrepo4#752]
I noticed an issue with Fedora 4.1.0 accepting a bad SPARQL Update and then behaving strangely. To reproduce:

`$ curl -X POST "http://localhost:8080/rest/"`

Response: `201 Created`
Location header: `http://localhost:8080/rest/07/70/13/4c/0770134c-92ea-4da6-9a43-4b749c45ef17`

`$ curl -X PATCH -H "Content-Type: application/sparql-update" --data-binary "@body.rdf" "http://localhost:8080/rest/07/70/13/4c/0770134c-92ea-4da6-9a43-4b749c45ef17"`

`body.rdf`:

    DELETE WHERE { <> <http://purl.org/dc/elements/1.1/title> ?o };
    DELETE WHERE { <> <http://example.org/> ?o };
    INSERT {
      <> <http://purl.org/dc/elements/1.1/title> "Rally Round the Flag" .
      <> <http://example.org/> "5" .
      <> <http://example.org/> "F941.708 IR4" .
    }
    WHERE { }

Response: `204 No Content`

From here on, GET and DELETE (maybe others too) to that URL return HTTP 500:

`$ curl -O http://localhost:8080/rest/07/70/13/4c/0770134c-92ea-4da6-9a43-4b749c45ef17`

Response body:

java.lang.IllegalArgumentException: The localName argument may not be null or zero-length at org.modeshape.common.util.CheckArg.isNotZeroLength(CheckArg.java:360) at org.modeshape.common.util.CheckArg.isNotEmpty(CheckArg.java:373) at org.modeshape.jcr.value.basic.NameValueFactory.create(NameValueFactory.java:175) at org.modeshape.jcr.value.basic.NameValueFactory.create(NameValueFactory.java:168) at org.modeshape.jcr.cache.document.DocumentTranslator.getProperties(DocumentTranslator.java:243) at org.modeshape.jcr.cache.document.LazyCachedNode.getProperties(LazyCachedNode.java:427) at org.modeshape.jcr.AbstractJcrNode.getProperties(AbstractJcrNode.java:2042) at org.fcrepo.kernel.impl.rdf.impl.PropertiesRdfContext.triplesFromProperties(PropertiesRdfContext.java:69) at org.fcrepo.kernel.impl.rdf.impl.PropertiesRdfContext.(PropertiesRdfContext.java:63) at sun.reflect.GeneratedConstructorAccessor58.newInstance(Unknown Source) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:526) at org.fcrepo.kernel.impl.FedoraResourceImpl.getTriples(FedoraResourceImpl.java:387) at org.fcrepo.kernel.impl.FedoraResourceImpl.getTriples(FedoraResourceImpl.java:374) at org.fcrepo.http.api.ContentExposingResource.getTriples(ContentExposingResource.java:397) at org.fcrepo.http.api.ContentExposingResource.getTriples(ContentExposingResource.java:393) at org.fcrepo.http.api.ContentExposingResource.getResourceTriples(ContentExposingResource.java:234) at org.fcrepo.http.api.ContentExposingResource.getContent(ContentExposingResource.java:187) at org.fcrepo.http.api.FedoraLdp.describe(FedoraLdp.java:190) at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171) at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104) at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:384) at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:342) at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101) at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) at org.glassfish.jersey.internal.Errors.process(Errors.java:315) at org.glassfish.jersey.internal.Errors.process(Errors.java:297) at org.glassfish.jersey.internal.Errors.process(Errors.java:267) at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297) at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254) at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030) at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) at org.eclipse.jetty.server.Server.handle(Server.java:497) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245) at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) at java.lang.Thread.run(Thread.java:745)

**Comment by awoods** [comment]
Thanks, @adolski. I have confirmed this bug. It is now being tracked in JIRA:
https://jira.duraspace.org/browse/FCREPO-1409

**Comment by awoods** [comment]
@adolski, are you in a position to be able to verify a fix to this issue by building either a feature branch or the master branch?

**Comment by adolski** [comment]
@awoods I'm not, sorry.

**Comment by awoods** [comment]
@adolski, no worries. It would be good to get your feedback after our next release. Or would you prefer to be provided a pre-built war file to have a look sooner?

**Comment by adolski** [comment]
@awoods There is no urgency on my end. I can verify the fix if you'd like, but I would only be re-running the same SPARQL Update statement above.

**Comment by awoods** [comment]
Thanks, @adolski. We are doing that, so hopefully all is well.
