### ISSUE TITLE
Version mismatch when trying to build from git as per the readme?

### ISSUE THREAD

**Issue by axfelix** [fcrepo4/fcrepo4#771]
Hi folks,

Getting this error when trying to follow the steps in the readme. I am categorically not a java guy so I'll refrain from speculating...

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project fcrepo-kernel: Fatal error compiling: invalid target release: 1.7

Thanks!

**Comment by awoods** [comment]
@axfelix, what version of Java is on your machine? i.e. What do you get when you run each of the following commands:
`java -version`
`javac -version`

**Comment by axfelix** [comment]
OpenJDK Runtime Environment (IcedTea6 1.13.6) (6b34-1.13.6-1ubuntu0.12.04.1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)

Do I need Sun Java?

**Comment by awoods** [comment]
It looks like you have Java6 installed. You need to upgrade to at least Java7. Starting next month, Fedora4 will then require Java8.

**Comment by axfelix** [comment]
Ah, d'oh, sorry; I used to know how to reconcile openJDK version numbers with the more popular ones, but I just took for granted I had at least 7; this is a pretty old 12.04 VM. I'll take the opportunity to install 8. Thanks!

**Comment by axfelix** [comment]
I'm afraid I'm still hitting this issue after installing java 8:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project fcrepo-kernel: Fatal error compiling: invalid target release: 1.7 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :fcrepo-kernel
garnett@lib-hf1:~/fcrepo4$ which java
/usr/bin/java
garnett@lib-hf1:~/fcrepo4$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

Does maven check elsewhere from the first location on my own path env when it's doing its thing?

**Comment by ajs6f** [comment]
Can you check `javac -version`? You may have installed the JVM but not the JDK.

**Comment by axfelix** [comment]
garnett@lib-hf1:~/fcrepo4$ javac -version
javac 1.8.0_45

**Comment by ajs6f** [comment]
Well, that wasn't it. Can you try with Java 7?

**Comment by axfelix** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project fcrepo-kernel: Fatal error compiling: invalid target release: 1.7 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :fcrepo-kernel
garnett@lib-hf1:~/fcrepo4$ java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

No dice!

**Comment by ajs6f** [comment]
That's truly bizarre. Can you try one last thing: explicitly set your `JAVA_HOME`, e.g.

`export JAVA_HOME=/where/ever/your/Java/7/home/actually/is`

`mvn clean install`

**Comment by axfelix** [comment]
That seems to have worked. Thanks! Like I said, not a Java person; JAVA_HOME was still pointing at the system's OpenJDK install.

**Comment by ajs6f** [comment]
Glad it worked.
