### ISSUE TITLE
Clarify in readme which repository.json is used by default?

### ISSUE THREAD

**Issue by axfelix** [fcrepo4/fcrepo4#773]
Would make it easier to know which file to tweak when testing stock configs.

(As an aside, I would actually like to know.)

**Comment by awoods** [comment]
This is the default with the production build:
https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-configs/src/main/resources/config/minimal-default/repository.json

Some tests use different configuration files. Which test do you have in mind?

**Comment by axfelix** [comment]
Sorry, I was doing a few things at once, you can omit the "with the test configuration" clause from my question and that'll do it. So, thanks :)
