### ISSUE TITLE
Simple federation test not working

### ISSUE THREAD

**Issue by axfelix** [fcrepo4/fcrepo4#775]
Hi folks,

Forgive me if I've misunderstood something from the documentation, but I'm not quite sure how to proceed here.

According to https://wiki.duraspace.org/display/FEDORA40/Filesystem+Federation, adding the below block to https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-configs/src/main/resources/config/minimal-default/repository.json and restarting Fedora should make a file in that directory called howdy.txt accessible at http://[base]:8080/rest/federated/howdy.txt, right?

        "externalSources" : {
          "federated-directory" : {
            "classname" : "org.fcrepo.connector.file.FedoraFileSystemConnector",
            "directoryPath" : "/home/axfelix/testfederation",
            "projections" : [ "default:/federated => /" ],
            "contentBasedSha1" : "false",
            "readonly" : true,
            "extraPropertiesStorage" : "none",
            "cacheTtlSeconds" : 5
          }
        }

I'm getting 404s. Do I need to do some kind of new install operation to ensure that config file is re-parsed? Thanks.

**Comment by awoods** [comment]
That should work. Does your Fedora process have read access to `/home/axfelix/testfederation`? 
What do you get if you make a request on: `http://[base]:8080/rest/federated/`?

**Comment by axfelix** [comment]
The directory is 777'ed, just to be on the safe side for the test ... getting 404s on just /rest/federated/ as well.

**Comment by awoods** [comment]
For my own testing purposes, which version of Fedora4 are you using?

**Comment by axfelix** [comment]
A git clone from master from Wednesday. I can pull changes if desired :)

**Comment by awoods** [comment]
@axfelix, I just tested your exact configuration (changing only the local directory path), and it worked as expected. That means that the issue is with the documentation.
Let me know if the following update helps:
https://wiki.duraspace.org/pages/diffpages.action?originalId=68068907&pageId=68068908

**Comment by axfelix** [comment]
Still no go. Any way it'd be loading the configuration from someplace other than https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-configs/src/main/resources/config/minimal-default/repository.json assuming I'm just following the Github readme to get up and running? Any, just to be clear, the externalSources json block doesn't need to be nested with any other?

**Comment by awoods** [comment]
How are you deploying your fcrepo4 application? `mvn jetty:run`? as a war file in tomcat? other?

**Comment by axfelix** [comment]
mvn jetty:run. Following the github docs pretty much to a T.

**Comment by awoods** [comment]
Place your updated repository.json file somewhere nearby.
Then run this command from the fcrepo-webapp directory:
`mvn -Dfcrepo.modeshape.configuration=file:///<absolute-path-to-repository.json> jetty:run`

p.s. What OS are you on?

**Comment by axfelix** [comment]
After doing that, I seem to be getting 503s when trying to hit the regular :8080/rest URL ... unfortunately not an improvement! This is 12.04.

**Comment by awoods** [comment]
Can you please paste the command you just tried here?

**Comment by axfelix** [comment]
Sure.

    mvn -Dfcrepo.modeshape.configuration=file:////home/garnett/fcrepo4/fcrepo-configs/src/main/resources/config/minimal-default/repository.json jetty:run

Hm, just noticed that file: wound up with four slashes after it rather than the three because I just pasted a / for the drive root ... let me try it with the three instead.

**Comment by axfelix** [comment]
Nope, that didn't make a difference.

**Comment by awoods** [comment]
I just tested the following command... which worked successfully:
`mvn -Dfcrepo.modeshape.configuration=file:///tmp/awoods/repository.json jetty:run`

With the following `repository.json` file:
```bash
{
    "name" : "repo",
    "jndiName" : "",
    "workspaces" : {
        "predefined" : ["default"],
        "default" : "default",
        "allowCreation" : true
    },
    "storage" : {
        "cacheName" : "FedoraRepository",
        "cacheConfiguration" : "${fcrepo.ispn.configuration:config/infinispan/leveldb-default/infinispan.xml}",
        "binaryStorage" : {
            "type" : "file",
            "directory" : "${fcrepo.binary.directory:target/binaries}",
            "minimumBinarySizeInBytes" : 4096
        }
    },

    "externalSources" : {
      "federated-directory" : {
        "classname" : "org.fcrepo.connector.file.FedoraFileSystemConnector",
        "directoryPath" : "/tmp/awoods/lib",
        "projections" : [ "default:/federated => /" ],
        "contentBasedSha1" : "false",
        "readonly" : true,
        "extraPropertiesStorage" : "none",
        "cacheTtlSeconds" : 5
      }
    },

    "security" : {
        "anonymous" : {
            "roles" : ["readonly","readwrite","admin"],
            "useOnFailedLogin" : false
        },
        "providers" : [
            { "classname" : "org.fcrepo.auth.common.BypassSecurityServletAuthenticationProvider" }
        ]
    },
    "node-types" : ["fedora-node-types.cnd"]
}
```

If that is still not working for you, could you please send me the output of you `jetty:run`. You can just pipe the terminal output to a file:
`mvn -D... jetty:run | tee some-file.txt`

**Comment by axfelix** [comment]
Nnnngh. Missing comma in the JSON. Working now. Thanks for telling me to pipe the terminal output so I actually read it. Thanks and sorry!
