### ISSUE TITLE
The front page should show the Fcrepo server version

### ISSUE THREAD

**Issue by jcoyne** [fcrepo4/fcrepo4#797]
Currently it show properties like  
```
fedora: repositoryJcrRepositoryVersion
    4.2.0.Final 
```
It would be nice for it to show a version for fcrepo too.

**Comment by awoods** [comment]
@jcoyne the version and build number of Fedora can currently be found on the front page:
http://locahost:8080/fcrepo
- (notice, this is on the context, such as "/fcrepo", not on "/fcrepo/rest")
