### ISSUE TITLE
System Requirements in readme should change to Java8

### ISSUE THREAD

**Issue by yinlinchen** [fcrepo4/fcrepo4#798]
Under Readme [https://github.com/fcrepo4/fcrepo4/blob/master/README.md] the System Requirements, the Java version is Java 7. Shouldn't change it to Java 8?

**Comment by awoods** [comment]
Yes, thanks:
https://github.com/fcrepo4/fcrepo4/commit/e69ad878eca93fa643f6b4413428a80da5cc616c
