### ISSUE TITLE
Change the way the REST API PUT endpoint works

### ISSUE THREAD

**Issue by adolski** [fcrepo4/fcrepo4#800]
I have a gripe about the PUT method in the REST API. I am finding that the way a container's RDF content is updated, by appending new triples to the bottom, is problematic. First, the example shows it working with Turtle but doesn't show how to accomplish it with other serializations. More importantly, it's not clear how to delete a triple, or if that is even possible. This severely impairs the utility of the PUT endpoint as one cannot use it to even change a title, for example. As far as I can tell, to delete a triple, I have to use SPARQL Update?

As an API user, I would expect that I should be able to retrieve a resource's RDF, manipulate it including adding/modifying/deleting triples, and PUT it back to the resource. Fedora should ignore its own managed triples in the update and update the resource's graph with the rest.

**Comment by awoods** [comment]
Thanks for the comment, @adolski. A detailed walkthrough of what you are actually doing would be helpful, as I am unable to reproduce what you are describing. 
Here are the steps that I perform successfully:
- Create resource:
`curl -i -XPUT -H"Content-Type: text/turtle" --data-binary @body.ttl localhost:8080/rest/book`
-- Where the file `body.ttl` contains whatever triples you want included in the new container.
- Get RDF
`curl -i -o body.out localhost:8080/rest/book`
- Copy `body.out` to `body.updated` and update with new or removed triples
- Push updated RDF
`curl -i -XPUT -H"Content-Type: text/turtle" --data-binary @body.updated localhost:8080/rest/book`
- See updates on subsequent GET requests! Success!

**Comment by adolski** [comment]
Thank you, @awoods. I see now that when the docs say to "Perform a GET to the current container's RDF content" before doing a PUT, they really aren't kidding. One cannot do GET-PUT-PUT, one must do GET-PUT-GET-PUT, as the former results in an HTTP 400 with the following error:

    Could not remove triple containing predicate http://fedora.info/definitions/v4/repository#lastModified to node /book

I was looking at that literally, like, "what the hell, I didn't remove that triple, it's right there." Now I get it: conflict prevention!

I guess that renders this issue invalid. However, can I make three suggestions:

* That the 400 error in this case be a 409 error
* That the error message be changed for thick people, like, "Cannot update the container as the given RDF is out-of-date based on the value of its fedora:lastModified triple."
* The documentation should mention that one cannot do GET-PUT-PUT.

**Comment by ajs6f** [comment]
`fedora:lastModified` is not user-modifiable. Maybe this is actually the wrong behavior...

**Comment by awoods** [comment]
@adolski, your three suggestions are all great.
- Please put in a ticket (hopefully with a Pull Request) for the 400 -> 409 change
-- In that same ticket you can include the message update
https://jira.duraspace.org/browse/FCREPO
- Could you please update the documentation?
