### ISSUE TITLE
Indexing transformations applied to binary nodes omit values

### ISSUE THREAD

**Issue by adolski** [fcrepo4/fcrepo4#814]
Steps to reproduce:

1. Create a binary node (ex.: `/binary`)
2. Add a `dc:title` triple to its `fcr:metadata`
3. Retrieve `/binary/fcr:transform/default`

The `title` key is present but points to an empty JSON array.

I have tried this with a custom indexing transformation as well, with the same result.

This may also be affecting other triples besides `dc:title`.

**Comment by awoods** [comment]
Likely related to: https://jira.duraspace.org/browse/FCREPO-1540

**Comment by ajs6f** [comment]
Not sure what it means to run an LDPath transform against a _binary_ resource... ?

**Comment by acoburn** [comment]
Closing this as `fcrepo-transform` has been removed from core and is no longer supported.
