### ISSUE TITLE
Scalability > 1000 children

### ISSUE THREAD

**Issue by TheStokoe** [fcrepo4/fcrepo4#839]
I have a federated filesystem with a node that has > 8000 children. Accessing any child object through the rest interface causes long delays 2.5 minutes or in many cases a complete timeout.

**Comment by awoods** [comment]
The same issue that impacts native F4 resources also affects filesystem projects.
https://wiki.duraspace.org/display/FEDORA4x/Large+Numbers+of+Containers#LargeNumbersofContainers-Federatedfilesystem

You will likely want to ensure that no single directory has more than ~2000 files.

**Comment by TheStokoe** [comment]
Native filesystem (ZFS) access isn't a problem I can enumerate the filesystem and sha1 each element without any significant overhead outside of fedora ?

**Comment by awoods** [comment]
I have updated the documentation:
https://wiki.duraspace.org/pages/diffpagesbyversion.action?pageId=67242872&selectedPageVersions=3&selectedPageVersions=4

I am not suggesting anything about your ZFS. I am suggesting that if you were to put 8000 resources at the top-level of your F4 repository you would see the same degraded performance as you see in the federation. As noted in the updated documentation, you will see much better performance if you structure your files in a hierarchy of directories, none of which containing more than ~3000 files.

There is a ticket with the underlying ModeShape project for this issue:
https://issues.jboss.org/browse/MODE-2109

Please add your vote to this issue if it is something you would like to see resolved.

**Comment by TheStokoe** [comment]
Thanks for clearing that up. 

I have now read through the modeshape ticket and will +1 in the hope that it doesn't keep getting bumped. 

A couple of points I would make: 

1) On a 24 core machine with 64GB of RAM and 4096 heap allocated I'm beginning to see timeouts and the impact of this around 1600 children (sub-directories) which is a little more acute than your testing has shown? 

2) I can't help but feel that this merits an open issue in your tracker just to signpost the problem and give a narrative of your engagement with upstream. Not everyone has the luxury of restructuring their hierarchy towards a balanced tree and if they can't then this is a showstopper.

**Comment by awoods** [comment]
Thanks for the details, @TheStokoe. It would be helpful if you added a ticket or documentation that would make the situation more clear for the next person.
