### ISSUE TITLE
500 error "Error converting InputStream to a BinaryValue"

### ISSUE THREAD

**Issue by jcoyne** [fcrepo4/fcrepo4#851]
In Fedora 4.1.1

**Comment by awoods** [comment]
@jcoyne, can you please describe the steps performed that result in this error?

**Comment by jcoyne** [comment]
I'm working on that. I was just wondering if the error message was familiar to you.

**Comment by awoods** [comment]
I do not recall having seen that error.

**Comment by jcoyne** [comment]
Okay, I'm putting this down to a client problem.  Tried to upload a file that had been read but not rewound.
