### ISSUE TITLE
"URI resources" are not created when using the Content-Location header

### ISSUE THREAD

**Issue by adolski** [fcrepo4/fcrepo4#925]
The [POST](https://wiki.duraspace.org/display/FEDORA44/RESTful+HTTP+API#RESTfulHTTPAPI-BluePOSTCreatenewresourceswithinaLDPcontainer) and PUT sections of the Fedora 4.4 wiki say that it is possible to use the `Content-Location` header to create a binary resource referring to an external URI.

The following do not work (they create an ordinary container node):

    curl -i -X POST -H "Content-Location: http://google.com/" "http://localhost:8080/fedora/rest/"
    curl -i -X PUT -H "Content-Location: http://google.com/" "http://localhost:8080/fedora/rest/something"

These, on the other hand, work (extrapolated from [PUT example 4](https://wiki.duraspace.org/display/FEDORA44/RESTful+HTTP+API#RESTfulHTTPAPI-YellowPUTCreatearesourcewithaspecifiedpath,orreplacethetriplesassociatedwitharesourcewiththetriplesprovidedintherequestbody.)):

    curl -i -X POST -H "Content-Type: message/external-body; access-type=URL; URL=\"http://google.com/\"" "http://localhost:8080/fedora/rest/"
    curl -i -X PUT -H "Content-Type: message/external-body; access-type=URL; URL=\"http://google.com/\"" "http://localhost:8080/fedora/rest/something-else"

**Comment by awoods** [comment]
Thanks, @adolski. Updated:
https://wiki.duraspace.org/pages/diffpagesbyversion.action?pageId=70586038&selectedPageVersions=2&selectedPageVersions=3
