### ISSUE TITLE
Can't update fcr:metadata in 4.4

### ISSUE THREAD

**Issue by adolski** [fcrepo4/fcrepo4#926]
Something has changed in Fedora 4.4 with regard to the way it handles updates to fcr:metadata. The following sequence works in 4.3 but not 4.4:

1) Create a binary

    curl -X POST -H "Content-Type: text/plain" -H "Slug: new-binary" "http://localhost:8080/fedora/rest/"

2) GET its fcr:metadata

    curl -H "Accept: text/turtle" "http://localhost:8080/fedora/rest/new-binary/fcr:metadata" > new-binary.rdf

3) Add some triples

    <> <http://example.org/bytestreamShape> <http://example.org/Bytestream/Shape/Original>;
       <http://example.org/bytestreamType> <http://example.org/Bytestream/Type/Master>;
       <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#hasMimeType> "audio/aiff";
       rdfs:Class <http://pcdm.org/models#File> .

4) PUT it back

    curl -X PUT -H "Content-Type: text/turtle" --data-binary "@new-binary.rdf" "http://localhost:8080/fedora/rest/new-binary/fcr:metadata"

The added triples are present in 4.3 but missing in 4.4.

Is this now the expected behavior, and if so, is there a workaround?

**Comment by awoods** [comment]
@adolski, thank you (again) for raising these helpful issues. It would be even more helpful if create these issues directly in our JIRA issue tracking system.
https://jira.duraspace.org/browse/FCREPO
Thanks!

**Comment by adolski** [comment]
https://jira.duraspace.org/browse/FCREPO-1803
