### ISSUE TITLE
Backup/Restore replacement

### ISSUE THREAD

**Issue by awoods** [fcrepo4/fcrepo4#946]
Since the current backup/restore (as well as import/export) feature is tightly tied to JCR, we should consider a more general alternative.

**Comment by DiegoPino** [comment]
This [ro-bundle specs and implementation](https://researchobject.github.io/specifications/bundle/) looks more semantic ready than adapting bagIT or other legacy ways.

Their approach is very aligned to LDP and they have even some tools. More over, they have very similar approaches on many things to what you/we are doing.

More on this:
http://www.researchobject.org/specifications/

**Comment by acoburn** [comment]
@awoods should this issue be moved to Jira and/or be addressed as part of the API specification effort?

**Comment by awoods** [comment]
@acoburn, since our approach to import/export has moved to client tooling, I am closing this issue.
