### ISSUE TITLE
Removing federated-directory results in NullPointerException

### ISSUE THREAD

**Issue by lbiedinger** [fcrepo4/fcrepo4#980]
Once fedora is started with federation configured:
```
"federated-directory" : {
            "classname" : "org.fcrepo.connector.file.FedoraFileSystemConnector",
            "directoryPath" : "/mnt/ingested",
            "projections" : [ "default:/federated => /" ],
            "contentBasedSha1" : "true",
            "readonly" : false,
            "extraPropertiesStorage" : "none",
            "cacheTtlSeconds" : 5
        }
```
Then once nodes under the federated node were visited via the browser and then fedora is restarted _without_ the federation configured.

Then visiting: http://localhost:8983/fedora/rest/federated/ results in a java NullPointerExeption ("java.lang.NullPointerException at org.modeshape.jcr.JcrSession.node...")* as opposed to a 404 not found.

Visiting any node below the federated node(http://localhost:8983/fedora/rest/federated/subfolder) results in a similar NullPointerException (java.lang.NullPointerException at org.modeshape.jcr.JcrSession.cachedNode...)* I'm not sure if this is simply because the ".../federated/..." node isn't available or if fedora kept some extra reference to the subfolder node around too.

*see attached file(s) for full trace 
[subfolder.txt](https://github.com/fcrepo4/fcrepo4/files/126586/subfolder.txt)
[federated.txt](https://github.com/fcrepo4/fcrepo4/files/126587/federated.txt)

**Comment by ajs6f** [comment]
Tracking with https://jira.duraspace.org/browse/FCREPO-1907
